using System.Text;

namespace Jiangyu.Codegen.Handlers;

/// <summary>One overridable method on a handler base type, already rendered to a C# signature.</summary>
public sealed record HandlerMethodDoc(string Name, string Signature);

/// <summary>A handler base type and the methods a modder overrides on it (the C# authoring path).</summary>
public sealed record HandlerBaseDoc(string Name, string Summary, IReadOnlyList<HandlerMethodDoc> Methods);

/// <summary>One settable field on a built-in handler (the KDL authoring path).</summary>
public sealed record HandlerFieldDoc(string Name, string Type, bool CodeOnly, IReadOnlyList<string> EnumValues);

/// <summary>A built-in handler subtype: the discriminator a modder names in <c>type="X"</c> and its fields.</summary>
public sealed record HandlerDoc(string Name, IReadOnlyList<HandlerFieldDoc> Fields);

/// <summary>
/// The whole page model: the handler base types and their overridable methods, the built-in
/// handler catalogue, and the condition and value-provider families. Built by the reflection
/// shell (Program); rendered here with no IO or reflection so it stays unit-testable.
/// </summary>
public sealed record HandlerModel(
    IReadOnlyList<HandlerBaseDoc> Bases,
    IReadOnlyList<HandlerDoc> Handlers,
    IReadOnlyList<string> Conditions,
    IReadOnlyList<string> ValueProviders);

/// <summary>Pure markdown rendering for the generated event-handler reference.</summary>
public static class HandlerDocEmit
{
    private const string DoNotEdit = "<!-- Generated by jiangyu-codegen-handlers. Do not edit by hand. -->";

    /// <summary>Render the whole reference page from the model.</summary>
    public static string Emit(HandlerModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(DoNotEdit);
        sb.AppendLine();
        sb.AppendLine("# Event handler reference");
        sb.AppendLine();
        sb.AppendLine("Every event handler the game ships, the methods you override to write your own, and the conditions it models. Generated from the game assembly, so it tracks the current build. See [Write a custom template type](/sdk/template-types) for the C# path and [Patch and clone templates](/templates) for wiring handlers from KDL.");
        sb.AppendLine();
        sb.AppendLine("An **event handler** is the unit of skill, perk, and status behaviour. Each entry in a `SkillTemplate` or `PerkTemplate`'s `EventHandlers` list is one handler the game ticks through its lifecycle. There are two ways to author one:");
        sb.AppendLine();
        sb.AppendLine("- **From data (KDL).** Add, edit, or remove any [built-in handler](#built-in-handlers) on a skill or perk and set its fields, naming the subtype with `type=\"<Name>\"`. No C# needed.");
        sb.AppendLine("- **From code (C#).** Subclass `SkillEventHandlerTemplate` and `SkillEventHandler` and override the [lifecycle methods](#lifecycle-methods) when no built-in does what you want.");

        EmitBases(sb, model.Bases);
        EmitHandlers(sb, model.Handlers);
        EmitNamedFamily(sb, "Conditions", model.Conditions,
            "The game models these reusable conditions (`TacticalCondition` subtypes). They live in handler fields typed `ITacticalCondition`, which are Odin-routed, so **KDL cannot set a condition** (those fields are marked **C# only** above). To gate a handler on a condition, write the handler in C# and put the check in the override body. The conditions the game already models:");
        EmitNamedFamily(sb, "Value providers", model.ValueProviders,
            "A value provider computes a number for a handler field typed `IValueProvider` (for example `ChangeProperty.ValueProvider`). These are Odin-routed too, so they are **C# only**. The providers the game ships:");

        return sb.ToString();
    }

    private static void EmitBases(StringBuilder sb, IReadOnlyList<HandlerBaseDoc> bases)
    {
        sb.AppendLine();
        sb.AppendLine("## Lifecycle methods");
        sb.AppendLine();
        sb.AppendLine("When you write a handler in C#, these are the methods you override. The template is the factory the data holds, and its `Create()` returns the handler the game ticks. Override only the ones you need; the rest keep the base's empty default. None of these carry doc comments in the game assembly, so this lists the signature you implement against.");

        foreach (var b in bases)
        {
            sb.AppendLine();
            sb.AppendLine($"### {b.Name}");
            if (!string.IsNullOrWhiteSpace(b.Summary))
            {
                sb.AppendLine();
                sb.AppendLine(b.Summary);
            }

            EmitMethodGroup(sb, b.Methods, "Events", m => m.Name.StartsWith("On", StringComparison.Ordinal));
            EmitMethodGroup(sb, b.Methods, "Predicates", m =>
                !m.Name.StartsWith("On", StringComparison.Ordinal) && IsPredicate(m.Name));
            EmitMethodGroup(sb, b.Methods, "Other", m =>
                !m.Name.StartsWith("On", StringComparison.Ordinal) && !IsPredicate(m.Name));
        }
    }

    private static bool IsPredicate(string name) =>
        name.StartsWith("Is", StringComparison.Ordinal)
        || name.StartsWith("Can", StringComparison.Ordinal)
        || name.StartsWith("Has", StringComparison.Ordinal)
        || name.StartsWith("Should", StringComparison.Ordinal);

    private static void EmitMethodGroup(StringBuilder sb, IReadOnlyList<HandlerMethodDoc> methods, string label, Func<HandlerMethodDoc, bool> predicate)
    {
        var rows = methods.Where(predicate).OrderBy(m => m.Name, StringComparer.Ordinal).ToList();
        if (rows.Count == 0) return;
        sb.AppendLine();
        sb.AppendLine($"**{label}**");
        sb.AppendLine();
        sb.AppendLine("| Method |");
        sb.AppendLine("| --- |");
        foreach (var m in rows)
            sb.AppendLine($"| `{m.Signature}` |");
    }

    private static void EmitHandlers(StringBuilder sb, IReadOnlyList<HandlerDoc> handlers)
    {
        sb.AppendLine();
        sb.AppendLine("## Built-in handlers");
        sb.AppendLine();
        sb.AppendLine($"The {handlers.Count} handlers the game ships. Name one in `type=\"<Name>\"` to add it, and set the fields listed; every field you do not set takes its type default. A field marked **C# only** is Odin-routed (an `ITacticalCondition` or `IValueProvider`) and cannot be set from KDL, so reach for the [C# path](#lifecycle-methods) when you need it. Enum fields list their allowed values.");
        sb.AppendLine();
        sb.AppendLine("```kdl");
        sb.AppendLine("append \"EventHandlers\" type=\"AddSkill\" {");
        sb.AppendLine("    set \"Event\" enum=\"AddEvent\" \"OnAttack\"");
        sb.AppendLine("    set \"SkillToAdd\" ref=\"SkillTemplate\" \"effect.bleeding\"");
        sb.AppendLine("}");
        sb.AppendLine("```");

        foreach (var h in handlers.OrderBy(h => h.Name, StringComparer.Ordinal))
        {
            sb.AppendLine();
            sb.AppendLine($"### {h.Name}");
            sb.AppendLine();
            if (h.Fields.Count == 0)
            {
                sb.AppendLine("No settable fields. It carries behaviour only.");
                continue;
            }
            sb.AppendLine("| Field | Type | Values / notes |");
            sb.AppendLine("| --- | --- | --- |");
            foreach (var f in h.Fields.OrderBy(f => f.Name, StringComparer.Ordinal))
            {
                var notes = f.CodeOnly
                    ? "**C# only** (Odin-routed): set in your handler in C#, see [Conditions](#conditions)."
                    : f.EnumValues.Count > 0
                        ? string.Join(", ", f.EnumValues.Select(v => $"`{v}`"))
                        : "";
                sb.AppendLine($"| `{f.Name}` | `{f.Type}` | {notes} |");
            }
        }
    }

    private static void EmitNamedFamily(StringBuilder sb, string title, IReadOnlyList<string> names, string intro)
    {
        if (names.Count == 0) return;
        sb.AppendLine();
        sb.AppendLine($"## {title}");
        sb.AppendLine();
        sb.AppendLine(intro);
        sb.AppendLine();
        foreach (var n in names.OrderBy(n => n, StringComparer.Ordinal))
            sb.AppendLine($"- `{n}`");
    }
}
