using System.Text;

namespace Jiangyu.Codegen.Hooks;

/// <summary>One payload field of a hook context, as carried into the catalogue.</summary>
public sealed record HookPayload(string Name, string Type, string Summary);

/// <summary>A resolved hook ready to emit: the SDK context, how it anchors, and its payload.</summary>
public sealed record HookModel(
    string Layer, string Name, string Context, string Kind, string Anchor, string Summary, IReadOnlyList<HookPayload> Payload);

/// <summary>
/// The pure emission for the hook generator: renders the resolved hooks into the
/// <c>HookCatalog</c> the SDK ships. Free of reflection and IO so it is unit-testable.
/// </summary>
public static class HookEmit
{
    /// <summary>Map a manifest hook kind to the <c>HookKind</c> member expression.</summary>
    public static string KindExpr(string kind) => kind switch
    {
        "event" => "global::Jiangyu.Sdk.HookKind.Event",
        "postfix" => "global::Jiangyu.Sdk.HookKind.Postfix",
        "synthetic" => "global::Jiangyu.Sdk.HookKind.Synthetic",
        _ => throw new ArgumentException($"unknown hook kind '{kind}'"),
    };

    private static string Escape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    /// <summary>Render one hook as a <c>HookDescriptor</c> initialiser line.</summary>
    public static string EmitDescriptor(HookModel h)
    {
        var payload = h.Payload.Count == 0
            ? "global::System.Array.Empty<global::Jiangyu.Sdk.HookPayloadField>()"
            : "new global::Jiangyu.Sdk.HookPayloadField[] { "
              + string.Join(", ", h.Payload.Select(p => $"new(\"{Escape(p.Name)}\", \"{Escape(p.Type)}\", \"{Escape(p.Summary)}\")"))
              + " }";
        return $"        new global::Jiangyu.Sdk.HookDescriptor(\"{Escape(h.Layer)}\", \"{Escape(h.Name)}\", "
             + $"typeof(global::Jiangyu.Sdk.{h.Context}), {KindExpr(h.Kind)}, "
             + $"\"{Escape(h.Anchor)}\", \"{Escape(h.Summary)}\", {payload}),";
    }

    /// <summary>Render the whole generated catalogue file.</summary>
    public static string EmitCatalog(IReadOnlyList<HookModel> hooks)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by jiangyu-codegen-hooks from the hook manifest. Do not edit by hand.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("namespace Jiangyu.Sdk;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Every hook a mod can subscribe to, generated from the hook manifest.</summary>");
        sb.AppendLine("public static class HookCatalog");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>The catalogue of hooks delivered through the hook bus.</summary>");
        sb.AppendLine("    public static global::System.Collections.Generic.IReadOnlyList<global::Jiangyu.Sdk.HookDescriptor> All { get; } = new global::Jiangyu.Sdk.HookDescriptor[]");
        sb.AppendLine("    {");
        foreach (var h in hooks) sb.AppendLine(EmitDescriptor(h));
        sb.AppendLine("    };");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
