using System.Text;

namespace Jiangyu.Codegen.Verbs;

/// <summary>
/// The pure emission logic for the verb generator: turning a group into its
/// namespace/class and rendering one resolved (verb, method) pair into member text
/// plus a whole file. Kept free of reflection and IO so it is unit-testable. Type-name
/// mapping lives in <see cref="TypeNames"/>.
/// </summary>
public static class VerbEmit
{
    /// <summary>"Tactical.Units" -> ("Jiangyu.Game.Tactical", "Units"); "Combat" -> ("Jiangyu.Game", "Combat").</summary>
    public static (string Namespace, string Class) GroupToNamespaceClass(string group)
    {
        var parts = group.Split('.');
        var cls = parts[^1];
        var ns = parts.Length > 1 ? "Jiangyu.Game." + string.Join('.', parts[..^1]) : "Jiangyu.Game";
        return (ns, cls);
    }

    /// <summary>
    /// Render one verb's member lines. <paramref name="receiver"/> is "self" (the verb
    /// takes <paramref name="selfTypeName"/> as its first argument and calls the method on
    /// it) or a literal expression yielding the instance. Mutating verbs get
    /// <c>[MutatingVerb]</c>.
    /// </summary>
    public static IReadOnlyList<string> EmitMember(
        string name, string methodName, string receiver, bool mutating,
        string returnTypeName, string selfTypeName, IReadOnlyList<string> paramTypeNames, string? summary)
    {
        var sig = new List<string>();
        var callArgs = new List<string>();
        if (receiver == "self")
            sig.Add($"{selfTypeName} self");
        for (var i = 0; i < paramTypeNames.Count; i++)
        {
            sig.Add($"{paramTypeNames[i]} p{i}");
            callArgs.Add($"p{i}");
        }

        var recv = receiver == "self" ? "self" : receiver;
        var call = $"{recv}.{methodName}({string.Join(", ", callArgs)})";
        var body = returnTypeName == "void" ? $"{{ {call}; }}" : $"=> {call};";

        var lines = new List<string>();
        if (!string.IsNullOrWhiteSpace(summary))
            lines.Add($"    /// <summary>{summary}</summary>");
        if (mutating)
            lines.Add("    [global::Jiangyu.Sdk.MutatingVerb]");
        lines.Add($"    public static {returnTypeName} {name}({string.Join(", ", sig)}) {body}");
        return lines;
    }

    /// <summary>Render a whole generated file: header + namespace + partial class + members.</summary>
    public static string EmitFile(string group, IReadOnlyList<IReadOnlyList<string>> members)
    {
        var (ns, cls) = GroupToNamespaceClass(group);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by jiangyu-codegen-verbs from the verb manifest. Do not edit by hand.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"public static partial class {cls}");
        sb.AppendLine("{");
        for (var i = 0; i < members.Count; i++)
        {
            foreach (var line in members[i]) sb.AppendLine(line);
            if (i < members.Count - 1) sb.AppendLine();
        }
        sb.AppendLine("}");
        return sb.ToString();
    }
}
