// Auto-generated by Jiangyu.Studio.Rpc.Generators. Do not edit.

export interface AgentSessionsFile {
  sessions?: AgentSessionMeta[];
}

export interface AgentSessionMeta {
  id: string;
  agentId?: string | null;
  agentName?: string | null;
  title?: string | null;
  firstMessage?: string | null;
  createdAt: number;
  updatedAt: number;
  currentModeId?: string | null;
  configValues?: Record<string, unknown> | null;
}

export interface CompileStartedAck {
  started: boolean;
}

export interface CompileStartedEvent {
  projectRoot: string;
}

export interface CompilePhaseEvent {
  phase: string;
}

export interface CompileStatusEvent {
  status: string;
}

export interface CompileProgressEvent {
  current: number;
  total: number;
}

export interface CompileLogEventPayload {
  level: string;
  message: string;
}

export interface PaneWindowOpenedAck {
  opened: boolean;
  windowId: string;
}

export interface StudioSettings {
  editorFontSize: number;
  uiFontScale: number;
  editorWordWrap?: string;
  sidebarHidden: boolean;
  sessionRestoreProject: boolean;
  sessionRestoreTabs: boolean;
  editorKeybindMode?: string;
  templateEditorMode?: string;
  aiEnabled: boolean;
  installedAgents?: InstalledAgent[];
}

export interface InstalledAgent {
  id: string;
  name: string;
  version?: string | null;
  distribution: string;
  command: string;
  args?: string[];
  packageName?: string | null;
  iconUrl?: string | null;
}

export interface ObjectInspectionResult {
  object: InspectedObjectIdentity;
  options: ObjectInspectionOptions;
  fields: InspectedFieldNode[];
}

export interface InspectedObjectIdentity {
  name: string;
  className: string;
  collection: string;
  pathId: number;
}

export interface ObjectInspectionOptions {
  maxDepth: number;
  maxArraySampleLength: number;
  truncated: boolean;
}

export interface InspectedFieldNode {
  name?: string | null;
  kind: string;
  fieldTypeName?: string | null;
  null?: boolean | null;
  truncated?: boolean | null;
  value?: unknown;
  count?: number | null;
  reference?: InspectedReference | null;
  elements?: InspectedFieldNode[] | null;
  fields?: InspectedFieldNode[] | null;
  reason?: string | null;
}

export interface InspectedReference {
  fileId?: number | null;
  pathId?: number | null;
  name?: string | null;
  className?: string | null;
}

export interface TemplateTypeEntry {
  className: string;
  count: number;
  classifiedVia: string;
  templateAncestor?: string | null;
}

export interface TemplateIdentity {
  collection: string;
  pathId: number;
}

export interface TemplateInstanceEntry {
  name: string;
  className: string;
  identity: TemplateIdentity;
  references?: TemplateEdge[] | null;
}

export interface TemplateEdge {
  fieldName: string;
  target: TemplateIdentity;
}

export interface TemplateReferenceEntry {
  source: TemplateIdentity;
  fieldName: string;
}

export interface AssetIndexStatus {
  state: string;
  reason?: string | null;
  assetCount?: number | null;
  indexedAt?: string | null;
}

export interface AssetExportResult {
  outputPath: string;
}

export interface AssetPreviewResult {
  data: string;
  mimeType: string;
}

export interface CompileFinishedEvent {
  success: boolean;
  bundlePath?: string | null;
  errorMessage?: string | null;
}

export interface CompileSummary {
  modName?: string | null;
  modVersion?: string | null;
  modAuthor?: string | null;
  modelReplacements: number;
  textureReplacements: number;
  spriteReplacements: number;
  audioReplacements: number;
  additionFiles: number;
  templateFiles: number;
  templatePatches: number;
  templateClones: number;
}

export interface FileEntry {
  name: string;
  path: string;
  isDirectory: boolean;
  isIgnored: boolean;
  size: number;
}

export interface DocsListResult {
  docs: DocListEntry[];
}

export interface DocListEntry {
  key: string;
  title: string;
}

export interface DocsReadResult {
  text: string;
}

export interface ConfigStatus {
  gamePath?: string | null;
  gameError?: string | null;
  gameUnityVersion?: string | null;
  unityEditorPath?: string | null;
  unityEditorError?: string | null;
  unityEditorVersion?: string | null;
  melonLoaderError?: string | null;
}

export interface EnumMembersResult {
  members: EnumMemberEntry[];
}

export interface EnumMemberEntry {
  name: string;
  value: number;
}

export interface TemplateIndexStatus {
  state: string;
  reason?: string | null;
  instanceCount?: number | null;
  typeCount?: number | null;
  indexedAt?: string | null;
}

export interface TemplateSearchResult {
  types: TemplateTypeEntry[];
  instances: TemplateInstanceEntry[];
  referencedBy?: Record<string, TemplateReferenceEntry[]> | null;
}

export interface TemplateQueryResult {
  kind: string;
  resolvedPath?: string | null;
  typeName?: string | null;
  typeFullName?: string | null;
  isWritable: boolean;
  patchScalarKind?: string | null;
  enumMemberNames?: string[] | null;
  enumMembers?: EnumMemberEntry[] | null;
  namedArrayEnumTypeName?: string | null;
  referenceTargetTypeName?: string | null;
  isLikelyOdinOnly?: boolean | null;
  members?: TemplateMember[] | null;
}

export interface TemplateMember {
  name: string;
  typeName: string;
  typeFullName?: string | null;
  isWritable: boolean;
  isInherited: boolean;
  isLikelyOdinOnly?: boolean | null;
  isCollection?: boolean | null;
  isScalar?: boolean | null;
  isTemplateReference?: boolean | null;
  isAssetReference?: boolean | null;
  patchScalarKind?: string | null;
  elementTypeName?: string | null;
  enumTypeName?: string | null;
  referenceTypeName?: string | null;
  isReferenceTypePolymorphic?: boolean | null;
  elementSubtypes?: string[] | null;
  namedArrayEnumTypeName?: string | null;
  enumMembers?: EnumMemberEntry[] | null;
  numericMin?: number | null;
  numericMax?: number | null;
  tooltip?: string | null;
  isHiddenInInspector?: boolean | null;
  isSoundIdField?: boolean | null;
}

export interface ProjectCloneEntry {
  templateType: string;
  id: string;
  file: string;
}

export interface TemplateValueResult {
  found: boolean;
  fields: InspectedFieldNode[];
}

