using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Jiangyu.Sdk.Analyzers;

/// <summary>
/// Emits the IL2CPP injection constructors every <c>[JiangyuType]</c> needs onto a
/// <c>partial</c> class, so a mod never hand-writes the identical boilerplate per
/// type. For a class that already declares one of the two constructors, only the
/// missing one is generated; a class that declares both gets nothing.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class JiangyuTypeConstructorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var sources = context.SyntaxProvider.ForAttributeWithMetadataName(
                JiangyuTypeAnalyzer.JiangyuTypeAttributeMetadataName,
                predicate: static (node, _) => node is ClassDeclarationSyntax declaration
                    && declaration.Modifiers.Any(static m => m.IsKind(SyntaxKind.PartialKeyword))
                    && declaration.ParameterList is null,
                transform: static (ctx, _) => Describe(ctx.TargetSymbol as INamedTypeSymbol))
            .Where(static source => source is not null);

        context.RegisterSourceOutput(sources, static (production, source) =>
            production.AddSource(source!.Value.HintName, SourceText.From(source.Value.Source, Encoding.UTF8)));
    }

    // String-only tuple so the incremental pipeline caches on value, never on a symbol.
    private static (string HintName, string Source)? Describe(INamedTypeSymbol? type)
    {
        // Skip what cannot be injected: an abstract, static, or generic class (the
        // analyzer reports the first two as JIA001); one whose base cannot take the
        // generated base(IntPtr) call (a plain object/managed base); or a structural
        // blocker — record, generic container, primary constructor, private injection
        // ctor — that the analyzer reports as JIA006. Emitting for any of these would
        // produce code that does not compile or a type that cannot actually be injected.
        if (type is null || type.IsAbstract || type.IsStatic || type.IsGenericType
            || !JiangyuTypeFacts.BaseAcceptsInjection(type)
            || JiangyuTypeFacts.UninjectableReason(type) is not null)
            return null;

        var (hasPointerCtor, hasParameterlessCtor) = JiangyuTypeFacts.InjectionConstructors(type);
        if (hasPointerCtor && hasParameterlessCtor)
            return null;

        return (BuildHintName(type), Render(type, hasPointerCtor, hasParameterlessCtor));
    }

    private static string Render(INamedTypeSymbol type, bool hasPointerCtor, bool hasParameterlessCtor)
    {
        // Outermost-first chain of containing types, so a nested [JiangyuType] is
        // reopened through its parents as partials. Each parent keeps its own kind and
        // type parameters so the reopened declaration matches the user's (the user must
        // declare the containers partial, or the generated parts fail to merge).
        var nesting = new List<string>();
        for (var outer = type.ContainingType; outer is not null; outer = outer.ContainingType)
            nesting.Insert(0, ContainerHeader(outer));

        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        var name = type.Name;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");

        var depth = 0;
        string Indent() => new string(' ', depth * 4);

        if (ns is not null)
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            depth++;
        }

        foreach (var header in nesting)
        {
            sb.AppendLine($"{Indent()}partial {header}");
            sb.AppendLine($"{Indent()}{{");
            depth++;
        }

        sb.AppendLine($"{Indent()}partial class {name}");
        sb.AppendLine($"{Indent()}{{");
        depth++;

        var first = true;
        if (!hasPointerCtor)
        {
            sb.AppendLine($"{Indent()}public {name}(global::System.IntPtr pointer) : base(pointer) {{ }}");
            first = false;
        }
        if (!hasParameterlessCtor)
        {
            if (!first)
                sb.AppendLine();
            sb.AppendLine($"{Indent()}public {name}()");
            sb.AppendLine($"{Indent()}    : base(global::Il2CppInterop.Runtime.Injection.ClassInjector.DerivedConstructorPointer<{name}>())");
            sb.AppendLine($"{Indent()}    => global::Il2CppInterop.Runtime.Injection.ClassInjector.DerivedConstructorBody(this);");
        }

        depth--;
        sb.AppendLine($"{Indent()}}}");

        for (var i = 0; i < nesting.Count; i++)
        {
            depth--;
            sb.AppendLine($"{Indent()}}}");
        }

        if (ns is not null)
            sb.AppendLine("}");

        return sb.ToString();
    }

    // The reopened declaration of a containing type: its kind and type parameters so it
    // merges with the user's declaration (e.g. "record struct Outer<T>").
    private static string ContainerHeader(INamedTypeSymbol type)
    {
        var keyword = type.IsRecord
            ? (type.IsValueType ? "record struct" : "record")
            : (type.IsValueType ? "struct" : "class");
        var typeParameters = type.TypeParameters.Length == 0
            ? string.Empty
            : "<" + string.Join(", ", type.TypeParameters.Select(p => p.Name)) + ">";
        return $"{keyword} {type.Name}{typeParameters}";
    }

    // The fully-qualified name is unique and (with generics excluded) a valid hint, so
    // it needs no lossy sanitisation that could collide two distinct types onto one file.
    private static string BuildHintName(INamedTypeSymbol type)
        => type.ToDisplayString() + ".JiangyuType.g.cs";
}
