using System.Text;
using Jiangyu.Sdk;

namespace Jiangyu.Codegen.Docs;

/// <summary>One verb row in the reference: where it lives, how it is called, what it does.</summary>
public sealed record VerbDoc(string Layer, string Class, string Member, string Signature, string Summary);

/// <summary>
/// The pure markdown rendering for the generated modder reference: the verb surface
/// (from the SDK's XML doc, so it covers generated and bespoke verbs alike) and the hook
/// surface (from <see cref="HookCatalog"/>). Free of IO and reflection so it is
/// unit-testable.
/// </summary>
public static class DocsEmit
{
    private const string DoNotEdit = "<!-- Generated by jiangyu-codegen-docs. Do not edit by hand. -->";

    /// <summary>Render the verb reference, grouped by layer then class.</summary>
    public static string EmitVerbs(IReadOnlyList<VerbDoc> verbs)
    {
        var sb = new StringBuilder();
        sb.AppendLine(DoNotEdit);
        sb.AppendLine();
        sb.AppendLine("# Verb reference");
        sb.AppendLine();
        sb.AppendLine("Every verb in the `Jiangyu.Game` namespace, generated from the SDK. Verbs are plain static calls that read and command the live game. See [the verbs guide](/sdk/verbs) for how and where to call them.");

        foreach (var layer in verbs.GroupBy(v => v.Layer).OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            sb.AppendLine();
            sb.AppendLine($"## {layer.Key}");
            foreach (var cls in layer.GroupBy(v => v.Class).OrderBy(g => g.Key, StringComparer.Ordinal))
            {
                sb.AppendLine();
                sb.AppendLine($"### {cls.Key}");
                sb.AppendLine();
                sb.AppendLine("| Verb | Description |");
                sb.AppendLine("| --- | --- |");
                foreach (var v in cls.OrderBy(v => v.Member, StringComparer.Ordinal))
                    sb.AppendLine($"| `{cls.Key}.{v.Signature}` | {Inline(v.Summary)} |");
            }
        }
        return sb.ToString();
    }

    /// <summary>Render the hook reference, grouped by layer.</summary>
    public static string EmitHooks(IReadOnlyList<HookDescriptor> hooks)
    {
        var sb = new StringBuilder();
        sb.AppendLine(DoNotEdit);
        sb.AppendLine();
        sb.AppendLine("# Hook reference");
        sb.AppendLine();
        sb.AppendLine("Every hook delivered through the hook bus, generated from the SDK. Subscribe with `Context.Hooks.Subscribe<T>` in a system's `OnInit` (see [the hooks guide](/sdk/#hooks) for the subscription model). Game-typed payloads arrive as `object`, so cast them in the handler.");

        foreach (var layer in hooks.GroupBy(h => h.Layer).OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            sb.AppendLine();
            sb.AppendLine($"## {layer.Key}");
            foreach (var hook in layer.OrderBy(h => h.Name, StringComparer.Ordinal))
            {
                sb.AppendLine();
                sb.AppendLine($"### {hook.Name}");
                sb.AppendLine();
                sb.AppendLine($"{Inline(hook.Summary)}");
                sb.AppendLine();
                var anchor = hook.Kind == HookKind.Synthetic ? "raised by Jiangyu" : $"`{hook.Anchor}`";
                sb.AppendLine($"- **Context:** `{hook.ContextType.Name}`");
                sb.AppendLine($"- **Source:** {hook.Kind.ToString().ToLowerInvariant()} ({anchor})");
                if (hook.Payload.Count > 0)
                {
                    sb.AppendLine();
                    sb.AppendLine("| Field | Type | Description |");
                    sb.AppendLine("| --- | --- | --- |");
                    foreach (var field in hook.Payload)
                        sb.AppendLine($"| `{field.Name}` | `{field.Type}` | {Inline(field.Summary)} |");
                }
            }
        }
        return sb.ToString();
    }

    // Collapse whitespace and escape the pipe so a summary stays inside its table cell.
    private static string Inline(string text)
        => string.Join(" ", (text ?? "").Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries)).Replace("|", "\\|");
}
