using System;
using Jiangyu.Codegen.Handlers;
using Xunit;

namespace Jiangyu.Codegen.Tests;

public class HandlerDocEmitTests
{
    private static HandlerModel Sample() => new(
        Bases:
        [
            new HandlerBaseDoc("SkillEventHandler", "The runtime behaviour.",
            [
                new HandlerMethodDoc("OnTurnStart", "void OnTurnStart()"),
                new HandlerMethodDoc("OnUpdate", "void OnUpdate(EntityProperties properties)"),
                new HandlerMethodDoc("IsUsable", "bool IsUsable()"),
                new HandlerMethodDoc("Create", "SkillEventHandler Create()"),
            ]),
        ],
        Handlers:
        [
            new HandlerDoc("AddSkill",
            [
                new HandlerFieldDoc("Event", "AddEvent", false, ["OnAttack", "OnUse"]),
                new HandlerFieldDoc("Condition", "ITacticalCondition", true, []),
                new HandlerFieldDoc("ShowHUDText", "bool", false, []),
            ]),
            new HandlerDoc("AccuracyStacks", []),
        ],
        Conditions: ["HitpointsPercentageCondition", "FactionCondition"],
        ValueProviders: ["SomeProvider"]);

    [Fact]
    public void Emit_renders_header_and_both_authoring_paths()
    {
        var md = HandlerDocEmit.Emit(Sample());
        Assert.StartsWith("<!-- Generated by jiangyu-codegen-handlers. Do not edit by hand. -->", md);
        Assert.Contains("# Event handler reference", md);
        Assert.Contains("## Lifecycle methods", md);
        Assert.Contains("## Built-in handlers", md);
    }

    [Fact]
    public void Emit_groups_methods_by_prefix()
    {
        var md = HandlerDocEmit.Emit(Sample());
        Assert.Contains("**Events**", md);
        Assert.Contains("| `void OnTurnStart()` |", md);
        Assert.Contains("**Predicates**", md);
        Assert.Contains("| `bool IsUsable()` |", md);
        Assert.Contains("**Other**", md);
        Assert.Contains("| `SkillEventHandler Create()` |", md);
        // Events sort before Predicates which sort before Other within a base.
        Assert.True(md.IndexOf("**Events**", StringComparison.Ordinal) < md.IndexOf("**Predicates**", StringComparison.Ordinal));
        Assert.True(md.IndexOf("**Predicates**", StringComparison.Ordinal) < md.IndexOf("**Other**", StringComparison.Ordinal));
    }

    [Fact]
    public void Emit_lists_enum_values_and_flags_odin_fields()
    {
        var md = HandlerDocEmit.Emit(Sample());
        Assert.Contains("| `Event` | `AddEvent` | `OnAttack`, `OnUse` |", md);
        Assert.Contains("**C# only**", md);
        // The Odin field row names the field but routes the modder to the C# path.
        Assert.Contains("| `Condition` | `ITacticalCondition` |", md);
    }

    [Fact]
    public void Emit_notes_behaviour_only_handlers()
    {
        var md = HandlerDocEmit.Emit(Sample());
        Assert.Contains("### AccuracyStacks", md);
        Assert.Contains("No settable fields. It carries behaviour only.", md);
    }

    [Fact]
    public void Emit_renders_condition_and_value_provider_families()
    {
        var md = HandlerDocEmit.Emit(Sample());
        Assert.Contains("## Conditions", md);
        Assert.Contains("- `FactionCondition`", md);
        Assert.Contains("## Value providers", md);
        Assert.Contains("- `SomeProvider`", md);
    }

    [Fact]
    public void Emit_omits_empty_families()
    {
        var model = Sample() with { Conditions = [], ValueProviders = [] };
        var md = HandlerDocEmit.Emit(model);
        Assert.DoesNotContain("## Conditions", md);
        Assert.DoesNotContain("## Value providers", md);
    }
}
