using Jiangyu.Codegen.Hooks;
using Xunit;

namespace Jiangyu.Codegen.Tests;

public class HookEmitTests
{
    [Theory]
    [InlineData("event", "global::Jiangyu.Sdk.HookKind.Event")]
    [InlineData("postfix", "global::Jiangyu.Sdk.HookKind.Postfix")]
    [InlineData("synthetic", "global::Jiangyu.Sdk.HookKind.Synthetic")]
    public void KindExpr_maps_each_kind(string kind, string expected)
        => Assert.Equal(expected, HookEmit.KindExpr(kind));

    [Fact]
    public void KindExpr_rejects_unknown_kind()
        => Assert.Throws<ArgumentException>(() => HookEmit.KindExpr("nonsense"));

    [Fact]
    public void EmitDescriptor_event_with_payload_renders_typeof_kind_anchor_and_fields()
    {
        var line = HookEmit.EmitDescriptor(new HookModel(
            "Tactical", "RoundStarted", "RoundStartedContext", "event", "TacticalManager.OnRoundStart",
            "A new tactical round began.",
            new[] { new HookPayload("Round", "int", "The round number that just started.") }));
        Assert.Contains("typeof(global::Jiangyu.Sdk.RoundStartedContext)", line);
        Assert.Contains("global::Jiangyu.Sdk.HookKind.Event", line);
        Assert.Contains("\"TacticalManager.OnRoundStart\"", line);
        Assert.Contains("new(\"Round\", \"int\", \"The round number that just started.\")", line);
    }

    [Fact]
    public void EmitDescriptor_empty_payload_uses_array_empty()
    {
        var line = HookEmit.EmitDescriptor(new HookModel(
            "Tactical", "MissionStarted", "MissionStartedContext", "synthetic", "",
            "A tactical mission loaded and is ready.", Array.Empty<HookPayload>()));
        Assert.Contains("global::System.Array.Empty<global::Jiangyu.Sdk.HookPayloadField>()", line);
        Assert.Contains("global::Jiangyu.Sdk.HookKind.Synthetic", line);
    }

    [Fact]
    public void EmitCatalog_wraps_descriptors_in_the_catalogue_class()
    {
        var catalog = HookEmit.EmitCatalog(new[]
        {
            new HookModel("Strategy", "LeaderHired", "LeaderHiredContext", "postfix", "Roster.HireLeader",
                "A leader was hired into the roster.",
                new[] { new HookPayload("Leader", "BaseUnitLeader", "The hired leader.") }),
        });
        Assert.Contains("// <auto-generated>", catalog);
        Assert.Contains("namespace Jiangyu.Sdk;", catalog);
        Assert.Contains("public static class HookCatalog", catalog);
        Assert.Contains("IReadOnlyList<global::Jiangyu.Sdk.HookDescriptor> All", catalog);
        Assert.Contains("global::Jiangyu.Sdk.HookKind.Postfix", catalog);
    }
}
