using Jiangyu.Codegen.Verbs;
using Xunit;

namespace Jiangyu.Codegen.Tests;

public class VerbEmitTests
{
    [Theory]
    [InlineData("System.Void", "void")]
    [InlineData("System.Int32", "int")]
    [InlineData("System.Boolean", "bool")]
    [InlineData("System.Single", "float")]
    [InlineData("System.String", "string")]
    [InlineData("Il2CppMenace.Tactical.Actor", "global::Il2CppMenace.Tactical.Actor")]
    public void MapTypeName_maps_primitives_and_qualifies_the_rest(string fullName, string expected)
        => Assert.Equal(expected, TypeNames.Map(fullName));

    [Fact]
    public void MapTypeName_flattens_nested_type_separator()
        => Assert.Equal("global::Some.Outer.Inner", TypeNames.Map("Some.Outer+Inner"));

    [Fact]
    public void Of_renders_constructed_generic_with_angle_brackets()
        => Assert.Equal("global::System.Nullable<int>", TypeNames.Of(typeof(int?)));

    [Fact]
    public void Of_renders_nested_generic_arguments_recursively()
        => Assert.Equal(
            "global::System.Collections.Generic.List<global::System.Collections.Generic.List<string>>",
            TypeNames.Of(typeof(System.Collections.Generic.List<System.Collections.Generic.List<string>>)));

    [Fact]
    public void Of_keeps_the_nested_type_segment_of_a_generic_outer()
    {
        // Regression: a type nested in a generic outer (Dictionary`2+Enumerator) must not be
        // truncated at the first backtick, which would drop the +Enumerator segment entirely.
        var rendered = TypeNames.Of(typeof(System.Collections.Generic.Dictionary<int, string>.Enumerator));
        Assert.Equal("global::System.Collections.Generic.Dictionary.Enumerator<int, string>", rendered);
    }

    [Theory]
    [InlineData("Tactical.Units", "Jiangyu.Game.Tactical", "Units")]
    [InlineData("Strategy.Campaign", "Jiangyu.Game.Strategy", "Campaign")]
    [InlineData("Combat", "Jiangyu.Game", "Combat")]
    public void GroupToNamespaceClass_splits_layer_from_class(string group, string ns, string cls)
    {
        var (actualNs, actualCls) = VerbEmit.GroupToNamespaceClass(group);
        Assert.Equal(ns, actualNs);
        Assert.Equal(cls, actualCls);
    }

    [Fact]
    public void EmitMember_self_receiver_read_calls_on_first_arg_and_omits_attribute()
    {
        var lines = VerbEmit.EmitMember(
            name: "Hitpoints", methodName: "GetHitpoints", receiver: "self", mutating: false,
            returnTypeName: "int", selfTypeName: "global::Il2CppMenace.Tactical.Actor",
            paramTypeNames: System.Array.Empty<string>(), summary: "The actor's current hitpoints.");
        var text = string.Join("\n", lines);
        Assert.Contains("/// <summary>The actor's current hitpoints.</summary>", text);
        Assert.DoesNotContain("MutatingVerb", text);
        Assert.Contains("public static int Hitpoints(global::Il2CppMenace.Tactical.Actor self) => self.GetHitpoints();", text);
    }

    [Fact]
    public void EmitMember_expression_receiver_mutating_tags_attribute_and_uses_expression()
    {
        var lines = VerbEmit.EmitMember(
            name: "Hire", methodName: "HireLeader",
            receiver: "global::Il2CppMenace.States.StrategyState.Get().Roster", mutating: true,
            returnTypeName: "global::Il2CppMenace.Strategy.BaseUnitLeader", selfTypeName: "unused",
            paramTypeNames: new[] { "global::Il2CppMenace.Strategy.UnitLeaderTemplate" }, summary: null);
        var text = string.Join("\n", lines);
        Assert.Contains("[global::Jiangyu.Sdk.MutatingVerb]", text);
        Assert.Contains(
            "public static global::Il2CppMenace.Strategy.BaseUnitLeader Hire(global::Il2CppMenace.Strategy.UnitLeaderTemplate p0) => global::Il2CppMenace.States.StrategyState.Get().Roster.HireLeader(p0);",
            text);
    }

    [Fact]
    public void EmitMember_void_uses_statement_body()
    {
        var lines = VerbEmit.EmitMember(
            name: "Despawn", methodName: "Die", receiver: "self", mutating: true,
            returnTypeName: "void", selfTypeName: "global::Il2CppMenace.Tactical.Actor",
            paramTypeNames: new[] { "bool" }, summary: null);
        var text = string.Join("\n", lines);
        Assert.Contains("public static void Despawn(global::Il2CppMenace.Tactical.Actor self, bool p0) { self.Die(p0); }", text);
    }

    [Fact]
    public void EmitFile_wraps_members_in_namespaced_partial_class()
    {
        var member = VerbEmit.EmitMember(
            "Hitpoints", "GetHitpoints", "self", false, "int",
            "global::Il2CppMenace.Tactical.Actor", System.Array.Empty<string>(), null);
        var file = VerbEmit.EmitFile("Tactical.Units", new[] { member });
        Assert.Contains("// <auto-generated>", file);
        Assert.Contains("namespace Jiangyu.Game.Tactical;", file);
        Assert.Contains("public static partial class Units", file);
        Assert.Contains("public static int Hitpoints(", file);
    }
}
